
spring:
  datasource:
    name: mysql
    url: jdbc:mysql:///gmall?rewriteBatchedStatements=true
    username: root
    password: shanshui
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.atguigu.**.bean
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#    default-executor-type: batch

